// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AirportMap: typeof import('./src/components/homeModule/AirportMap.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Facility: typeof import('./src/components/homeModule/Facility.vue')['default']
    FlightList: typeof import('./src/components/FlightList.vue')['default']
    FlightSchedule: typeof import('./src/components/homeModule/FlightSchedule.vue')['default']
    Food: typeof import('./src/components/homeModule/Food.vue')['default']
    Layout: typeof import('./src/components/layout/Layout.vue')['default']
    LeafletMap: typeof import('./src/components/LeafletMap.vue')['default']
    Loading: typeof import('./src/components/animation/Loading.vue')['default']
    LoopTextContainer: typeof import('./src/components/LoopTextContainer.vue')['default']
    More: typeof import('./src/components/homeModule/More.vue')['default']
    NaviLayout: typeof import('./src/components/layout/NaviLayout.vue')['default']
    OpenLayer: typeof import('./src/components/OpenLayer.vue')['default']
    PasswordKeyboard: typeof import('./src/components/PasswordKeyboard.vue')['default']
    PlanRoute: typeof import('./src/components/animation/PlanRoute.vue')['default']
    RollUpContainer: typeof import('./src/components/RollUpContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScanFace: typeof import('./src/components/homeModule/ScanFace.vue')['default']
    ShopLoop: typeof import('./src/components/ShopLoop.vue')['default']
    Shopping: typeof import('./src/components/homeModule/Shopping.vue')['default']
    SubLayout: typeof import('./src/components/layout/SubLayout.vue')['default']
    Traffic: typeof import('./src/components/homeModule/Traffic.vue')['default']
  }
}

export {}
